version: '3.8'

services:
  # 前端服务
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE_URL=http://localhost:8080
    depends_on:
      - backend
    networks:
      - app-network

  # 后端服务
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=hr_system
      - DB_USER=root
      - DB_PASSWORD=hr123456
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - WEBDAV_URL=http://webdav:8080/webdav
      - WEBDAV_USERNAME=admin
      - WEBDAV_PASSWORD=admin123
      - PAPERLESS_API_URL=http://paperless:8000/api
      - PAPERLESS_API_TOKEN=${PAPERLESS_API_TOKEN:-}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL:-https://api.openai.com/v1}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-3.5-turbo}
    depends_on:
      - mysql
      - redis
      - webdav
    networks:
      - app-network

  # MySQL 数据库
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: hr123456
      MYSQL_DATABASE: hr_system
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  # WebDAV 文件存储
  webdav:
    image: bytemark/webdav:latest
    ports:
      - "8081:8080"
    environment:
      AUTH_TYPE: Basic
      USERNAME: admin
      PASSWORD: admin123
    volumes:
      - webdav-data:/var/lib/dav
    networks:
      - app-network

  # Paperless-NGX 文档管理系统（可选）
  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    ports:
      - "8000:8000"
    environment:
      PAPERLESS_REDIS: redis://redis:6379
      PAPERLESS_DBHOST: mysql
      PAPERLESS_DBNAME: paperless
      PAPERLESS_DBUSER: paperless
      PAPERLESS_DBPASS: paperless123
      PAPERLESS_SECRET_KEY: paperless-secret-key-change-me
      PAPERLESS_URL: http://localhost:8000
      PAPERLESS_TIME_ZONE: Asia/Shanghai
      PAPERLESS_OCR_LANGUAGE: chi_sim+eng
    volumes:
      - paperless-data:/usr/src/paperless/data
      - paperless-media:/usr/src/paperless/media
      - paperless-export:/usr/src/paperless/export
      - paperless-consume:/usr/src/paperless/consume
    depends_on:
      - mysql
      - redis
    networks:
      - app-network

  # Redis 缓存
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network

volumes:
  mysql-data:
  redis-data:
  webdav-data:
  paperless-data:
  paperless-media:
  paperless-export:
  paperless-consume:

networks:
  app-network:
    driver: bridge