server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: hr-management-system
  
  profiles:
    active: dev
  
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:hr_system}?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&useLocalSessionState=true&rewriteBatchedStatements=true
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:hr123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  
  redis:
    host: ${REDIS_HOST:redis}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    database: 0
    timeout: 5000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss

# WebDAV 配置
webdav:
  url: ${WEBDAV_URL:http://localhost:8081/webdav}
  username: ${WEBDAV_USERNAME:admin}
  password: ${WEBDAV_PASSWORD:admin123}
  base-path: ${WEBDAV_BASE_PATH:/hr-files}

# Paperless-ngx 配置
paperless:
  api:
    url: ${PAPERLESS_API_URL:http://localhost:8000/api}
    token: ${PAPERLESS_API_TOKEN:}
  
# OpenAI 配置
openai:
  api:
    key: ${OPENAI_API_KEY:}
    base-url: ${OPENAI_BASE_URL:https://api.openai.com/v1}
    model: ${OPENAI_MODEL:gpt-3.5-turbo}
    timeout: 30000

# JWT 配置
jwt:
  secret: ${JWT_SECRET:hrManagementSystemSecretKey2024}
  expiration: 86400000 # 24小时

# 文件上传配置
file:
  upload:
    path: ${FILE_UPLOAD_PATH:/tmp/uploads}
    max-size: 104857600 # 100MB

# 日志配置
logging:
  level:
    com.hr: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/hr-management.log

---
# 开发环境配置
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    show-sql: true

---
# Docker 环境配置
spring:
  config:
    activate:
      on-profile: docker
  jpa:
    show-sql: false
  redis:
    host: ${REDIS_HOST:redis}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    database: 0
    timeout: 5000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

logging:
  level:
    com.hr: INFO