# 本地开发环境配置
spring:
  config:
    activate:
      on-profile: local
  
  datasource:
    url: jdbc:mysql://localhost:3306/hr_system?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  
  redis:
    host: localhost
    port: 6379
    password: 
    database: 0
    timeout: 5000ms

# MinIO 配置（本地开发可选）
minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin123
  bucket-name: hr-files

# 文件上传配置
file:
  upload:
    path: ./uploads
    max-size: 104857600 # 100MB

# 日志配置
logging:
  level:
    com.hr: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"